### ISSUE TITLE
Don't Log flag?

### ISSUE THREAD

**Issue by Neo-X** [DistributedClocks/GoVector#1]
Hello,

Say I am very pleased with the logging and believe everything works perfectly. I don't want to change my code but I now longer want to log large number of files for my system. 

Is there a method/flag in the library to disable logging completely? I see there are some to print out the logging to the screen, but none to disable.

**Comment by bestchai** [comment]
Hi, thanks for the feature suggestion. Unfortunately, we don't support this yet, but it wouldn't be difficult to add. We'll comment on this issue once it's in the master branch. It'll probably take a few days.

**Comment by arcaneiceman** [comment]
Hey! Its updated with the Disable Logging API call which should disable any further Logging after its called.

**Comment by Neo-X** [comment]
Awesome, thanks.
