### ISSUE TITLE
Create a GoLogConfig struct to be passed into GoLog library on initialization

### ISSUE THREAD

**Issue by mikegfink** [DistributedClocks/GoVector#11]
GoLog's initialize functions (Initialize and InitializeMutipleExecutions) do not accept parameters for GoVec settings.

Create a struct that holds the appropriate settings (gv.printonscreen (ShouldYouSeeLoggingOnScreen) gv.VConWire  (ShouldISendVectorClockonWire),gv.debugmode (Debug), gv.realtime = false etc), modify the initialize functions to accept this struct and modify the GoLog struct to store and use the configuration struct.

**Comment by vaastav** [comment]
Added in #49
