### ISSUE TITLE
Error: Logical clock values for each host must start at 1

### ISSUE THREAD

**Issue by annygakh** [DistributedClocks/GoVector#31]
**Issue:**
When I have several clients logging events to the same log file, only the first client of the library has an entry with a vector clock starting at 1. The rest of the clients do not have an entry where the vector clock starts at 1 for them. As a result, when I upload a log file to https://bestchai.bitbucket.io/shiviz/ I get an error saying
```
Logical clock values for each host must start at 1.
The clock value for the first event for host "34784" is 2.
```

**Code used to obtain the problem:**
This is the structure of my project
- network
- - network.go
- client.go
- server.go
 
These extensions of these files should be changed to '.go'
[client.txt](https://github.com/DistributedClocks/GoVector/files/1822313/client.txt)
[network.txt](https://github.com/DistributedClocks/GoVector/files/1822314/network.txt)
[server.txt](https://github.com/DistributedClocks/GoVector/files/1822315/server.txt)

```
# How to run this project
$ server.go # in one terminal, leave it running
$ client.go <IP:port of the server> # run this several times, in different terminals 
```

<s>**Proposed fix:** If the log file exists, we still need to log some kind of event, which will result in having an entry with a vector clock starting at 1.
[patchFix.txt](https://github.com/DistributedClocks/GoVector/files/1822321/patchFix.txt)</s>
Update: Actually I don't know enough about the project to be sure that this will work. In particular, Im not sure why we have different execution numbers, and do entries for new processes must start with vector clock 1?

**Comment by vaastav** [comment]
@annygakh  multiple clients shouldn't be logging to the same file. That is the issue here.
