### ISSUE TITLE
Little Code Error

### ISSUE THREAD

**Issue by DiegoCCMM** [DistributedClocks/GoVector#61]
Hi!

I've used this library in college for a little proyect and all the teammates I meet had the same problem I had.

In the govec program, inside the govec folder, line 208 has a bug where you passed 3 arguments to the function dec.Decode(). An error pop up saying how it's supposed to be and, actually, in the line 183 is correctly used. So i changed it to err = dec.Decode(&d.Payload) and it works.

I see is an easy fix, but using an IDE (for example Goland) it warns you and tries to prevent you from changing any file that is an external library. Maybe, for an even more amateur programmer than me, this could be the end of the work for a while.

**Comment by shayanh** [comment]
This is already resolved.
