### ISSUE TITLE
Faulty Vector Clock Comparison

### ISSUE THREAD

**Issue by pfandzelter** [DistributedClocks/GoVector#68]
Unfortunately there appears to be a bug in the vector clock comparison implementation:
https://github.com/DistributedClocks/GoVector/blob/db949c81a0af441c4f1c960e436ca4f7e678b415/govec/vclock/vclock.go#L138

This simple test will fail:

```go
func TestCompareDifferentLengths(t *testing.T) {
	n1 := New()
	n2 := New()

	n1.Set("a", 1)
	n1.Set("b", 1)

	n2.Set("b", 1)
	n2.Set("c", 1)
	n2.Set("d", 1)

	if n1.Compare(n2, Descendant) {
		failComparison(t, "Clocks are defined as Descendant: n1 = %s | n2 = %s", n1, n2)
	}
}
```

The comparison function will detect that (B:1, C:1, D:1) is a descendant of (A:1, B1:), although they are concurrent.
I don't have a fix for this issue, but I'd like to warn future users of the package.
There does not seem to be any ongoing maintenance.
For now, we have created a fork of just the `vclock` implementation: https://github.com/OpenFogStack/vclock

**Comment by shayanh** [comment]
Hi @pfandzelter,

Thanks for the report. Pull request #69 resolves this.
